# Python Django
# Test a Django project

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '2.7'
    architecture: 'x64'

- script: |
    python -m pip install --upgrade pip setuptools wheel
    pip install --target ./web_app/lib/ --requirement ./web_app/requirements.txt
    pip install unittest-xml-reporting
    condition: succeededOrFailed()
    displayName: 'Install prerequisites'

- script: |
    pushd '$(projectRoot)'
    python ./web_app/manage.py test --testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner --no-input
    condition: succeededOrFailed()
    displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: "**/TEST-*.xml"
    testRunTitle: 'Python $(PYTHON_VERSION)'
